export const GET_ALBUM_START = "GET_ALBUM_START";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAIL = "GET_ALBUM_FAIL";

export const DELETE_ALBUM_START = "DELETE_ALBUM_START";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAIL = "DELETE_ALBUM_FAIL";
